source 'https://rubygems.org'

ruby '2.6.6'
gem 'rails', '4.2.11'

gem 'sass-rails', '~> 5.0.3'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 2.7.1'

gem 'jquery-rails'
gem 'haml'
gem 'protected_attributes'

gem 'test-unit'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'sqlite3', '~> 1.3.11'
  gem 'byebug'
  gem 'database_cleaner'  # to clear Cucumber's test database between runs
  gem 'capybara'          # lets Cucumber pretend to be a web browser
  gem 'launchy'           # a useful debugging aid for user stories
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'  # some pre-fabbed step definitions  
end

group :production do
  gem 'pg'
end

gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem "omniauth-rails_csrf_protection", "~> 1.0"
gem 'dotenv-rails'